# fly.toml app configuration file generated for mylibsuper on 2025-10-05T21:18:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mylibsuper'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
